language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c
  'CREATE DATABASE chitter_test;
   CREATE TABLE peeps(
     id SERIAL PRIMARY KEY,
     peep VARCHAR(140),
     user_email VARCHAR(30),
     time VARCHAR(30)
     );

   CREATE TABLE users(
     id SERIAL PRIMARY KEY,
     email VARCHAR(60),
     password VARCHAR(140)
     );'

script:
  - bundle exec rspec
